# Maquina administrativa principal
allow 10.130.221.13;

# Maquina administrativa secundaria
# allow 10.130.221.14;

# Red administrativa
# allow 10.130.221.0/24;

# Bloquear cualquier otro origen
deny all;